apiVersion: v1
kind: Service
metadata:
  name: vibe-media
spec:
  selector:
    app: vibe-media-t1
  ports:
    - port: 80        # clusterâ€‘internal port
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
