apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibe-media-t2
  labels:
    app: vibe-media-t2
spec:
  replicas: 1
  revisionHistoryLimit: 2  # Keep only the last 2 revisions
  selector:
    matchLabels:
      app: vibe-media-t2
  template:
    metadata:
      labels:
        app: vibe-media-t2
    spec:
      containers:
        - name: web
          image: dzhemaptula/vibe-media:0.11.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: social_media.settings
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
