apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vibe-media-t2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: vibe-t2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vibe-media-t2
                port:
                  number: 80
